service: eco-management-cloud

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512

package:
  individually: true

custom:
  supersecret: ${ssm:/aws/reference/secretsmanager/${opt:stage, 'dev'}/eco-management~true}

functions:
  createUser:
    handler: src/users/index.handler
    environment:
      MONGODB_URI: ${self:custom.supersecret.MONGO_URI}
      DATABASE_NAME: ${self:custom.supersecret.MONGO_DATABASE}
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    package:
      exclude:
        - src/**
      include:
        - src/users/index.js
        - shared/**
